CREATE TABLE GAMES (
  GAME_ID      NUMBER        NOT NULL,
  TITLE        VARCHAR2(120) NOT NULL,
  GENRE        VARCHAR2(60),
  RELEASE_YEAR NUMBER(4,0),
  CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
  PRICE        NUMBER(10,2),
  CONSTRAINT PK_GAMES PRIMARY KEY (GAME_ID)
);

CREATE TABLE REVIEWS (
  REVIEW_ID    NUMBER        NOT NULL,
  GAME_ID      NUMBER        NOT NULL,
  RATING       NUMBER(2,1),
  REVIEW_TEXT  VARCHAR2(255),
  CREATED_AT   DATE          DEFAULT SYSDATE NOT NULL,
  CONSTRAINT PK_REVIEWS PRIMARY KEY (REVIEW_ID),
  CONSTRAINT FK_REVIEWS_GAME 
    FOREIGN KEY (GAME_ID) REFERENCES GAMES (GAME_ID)
      ON DELETE CASCADE
);
