name: build-and-deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: gamehub   # pom.xml está em /gamehub
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn -B -DskipTests clean package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: gamehub/target/*.jar   # mantém como está
          if-no-files-found: error

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app-jar
          path: ./artifact

      - name: List artifact contents (debug)
        run: |
          echo "== artifact tree =="
          ls -R ./artifact || true

      - name: Locate jar path
        id: pkg
        run: |
          set -e
          FILE=$(find ./artifact -type f -name "*.jar" | head -n1)
          if [ -z "$FILE" ]; then
            echo "No JAR found under ./artifact"
            exit 1
          fi
          echo "Found JAR: $FILE"
          echo "path=$FILE" >> $GITHUB_OUTPUT

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: app-games-rm98410
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ steps.pkg.outputs.path }}
